url: https://mcr.jesus.cam.ac.uk
baseurl: "/"

source:      ""
destination: "../build"
 
# Site settings
title: Jesus College MCR
email: kd400@cam.ac.uk
description: "Jesus College MCR (Graduate Society), University of Cambridge."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ed0909
  secondary: 8a0000
  secondary-dark: 333

# Team names, titles and social links. Any font awesome icon can be used (drop the fa)
people:
- name: Taylor Saunders-Wood
  pic: 2017-Taylor-Saunders-Wood
  position: President
  social:
    - title: paper-plane
      url: https://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=aQdyuDi7KG7H2oAxa6G1_N5KhkQaNHytGGuhzg3LD1E=

- name: Jennifer Holian
  pic: 2017-Jennie-Holian
  position: Vice-President
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=BjVjndDJCy1j5clAsHoPGwZsF26Z01BiXnH93GM-90mBaykr5bmEsUAFgjdSeY23

- name: Bee Fonseka
  pic: 2017-Bee-Fonseka
  position: Secretary
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=s9z7dIADNWoax1H0hTLY2pmMl7bqQmfQB1y5mPyp-NY=

- name: Emma Findlay
  pic: 2017-Emma-Findlay
  position: Treasurer
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=HSGVFgyqUuTpXgpbKaHWPcwru6rOMMLIgQZcr7_WnMU=

- name: Anika Krause
  pic: 2017-Anika-Krause
  position: Social Officer
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=hZK4Mk1fNQkFU0pc8KqmnoqmebM4rYreCHLtWjktEIc=

- name: David Jarvis
  pic: 2017-David-Jarvis
  position: Social Officer
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=hZK4Mk1fNQkFU0pc8KqmnoqmebM4rYreCHLtWjktEIc=

- name: Joy Shih
  pic: 2017-Joy-Shih
  position: Women's Welfare
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=gRdP7HrS7q6H_9UaOniDlG8LBgc97_eANTCGYNWoPY4=

- name: Keerthi Senthil
  pic: 2017-tbd
  position: Men's Welfare
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=01nSdl5o8KNFEmhrYtN4C-Kw==&c=c3m-YX2_hr5tGx4ugoYOw_O-Oj-W6h0z7gzNeUIQfXY=

- name: Lena Moore
  pic: 2017-tbd
  position: LGBT Welfare
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=01nSdl5o8KNFEmhrYtN4C-Kw==&c=c3m-YX2_hr5tGx4ugoYOw_O-Oj-W6h0z7gzNeUIQfXY=
  # TODO: fix url 
#  social:
#    - title: paper-plane
#      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=-kvR76zRmmVis3kuLgDaoNEs7Ekh0gFRoDOmaFkQZ5I=

- name: Natalia Elvira Astoreca
  pic: 2017-Natalia-Elvira
  position: International Welfare
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=SQY8J09AaGPG1NYnTNlebzFWZ8fjsCOK70k3yE3uYia1l0vuNk8VUzWKcAJHZ1Xr

- name: Cai Read
  pic: 2017-Cai-Read
  position: Academic Officer
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=WWrM2esLbjx5625bc_hLlIVyGyX0rAF6bXR4E28yh3c=

- name: Syamala Roberts
  pic: 2017-Syamala-Roberts
  position: Green Officer
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=y5IWlfBaTDz_VwDy137-0Q_SzB6h51UpnvC6Qjbdvuc=

- name: Silvia Basilico
  pic: 2016-Silvia-Basilico
  position: College Council Representative
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=XkoLye-sVWSQj1YOq3-VY0tr8UEt1ALcCKJrTNX_MGGjC1u5-v9k4avalobib5nj

- name: Samuel Plummer
  pic: 2017-tbd
  position: Sports Officer
  social:
    - title: paper-plane
      url: https//www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=e-pI041rLRnWFInyuaBr5imkpKJsGBigigE6kFRIuG8=

- name: Krittika D'Silva
  pic: 2017-Krittika-DSilva 
  position: Webmaster
  social:
    - title: paper-plane
      url: mailto:mcr-webmaster@jesus.cam.ac.uk

# Team names, titles and social links. Any font awesome icon can be used (drop the fa)
fellows:
- name: Dr Sybil Stacpoole
  pic: Fellow-Stacpoole-150x150
  position: Assistant Deputy Graduate Tutor
  social:
    - title: paper-plane
      url: mailto:graduate-tutor@jesus.cam.ac.uk

- name: Professor Tim Wilkinson
  pic: Fellow-Tim-150x150
  position: Graduate Tutor
  social:
    - title: paper-plane
      url: mailto:graduate-tutor@jesus.cam.ac.uk

- name: Vanessa Bowman
  pic: Vanessa
  position: Graduate Administrator
  social:
    - title: paper-plane
      url: mailto:graduate-tutor@jesus.cam.ac.uk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/JesusCollegeCam
  - title: facebook
    url: https://www.facebook.com/groups/jesus.newgrads2011
  - title: github
    url: https://github.com/JJMinton/JesusMCRsite
  - title: linkedin
    url: https://www.linkedin.com/groups?home=&gid=872067&trk=my_groups-tile-grp

# Postal address (add as many lines as necessary)
address:
  - line: Jesus Lane
  - line: Cambridge, CB58BL

# Build settings
markdown: kramdown
permalink: pretty
