url: https://mcr.jesus.cam.ac.uk
baseurl: "/"

source:      ""
destination: "../build"
 
# Site settings
title: Jesus College MCR
email: kd400@cam.ac.uk
description: "Jesus College MCR (Graduate Society), University of Cambridge."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ed0909
  secondary: 8a0000
  secondary-dark: 333

# Team names, titles and social links. Any font awesome icon can be used (drop the fa)
people:
- name: Taylor Saunders-Wood
  pic: 2017-Taylor-Saunders-Wood
  position: President
  social:
    - title: paper-plane
      url: mailto:mcr-president@jesus.cam.ac.uk

- name: Jennifer Holian
  pic: 2017-Jennie-Holian
  position: Vice-President
  social:
    - title: paper-plane
      url: mailto:mcr-vice-president@jesus.cam.ac.uk

- name: Bee Fonseka
  pic: 2017-Bee-Fonseka
  position: Secretary
  social:
    - title: paper-plane
      url: mailto:mcr-secretary@jesus.cam.ac.uk

- name: Emma Findlay
  pic: 2017-Emma-Findlay
  position: Treasurer
  social:
    - title: paper-plane
      url: mailto:mcr-treasurer@jesus.cam.ac.uk

- name: Anika Krause
  pic: 2017-Anika-Krause
  position: Social Officer
  social:
    - title: paper-plane
      url: mailto:mcr-social@jesus.cam.ac.uk

- name: David Jarvis
  pic: 2017-David-Jarvis
  position: Social Officer
  social:
    - title: paper-plane
      url: mailto:mcr-social@jesus.cam.ac.uk

- name: Joy Shih
  pic: 2017-Joy-Shih
  position: Women's Welfare
  social:
    - title: paper-plane
      url: mailto:mcr-womens@jesus.cam.ac.uk

- name: Keerthi Senthil
  pic: 2017-Keerthi-Senthil
  position: Men's Welfare
  social:
    - title: paper-plane
      url: mailto:mcr-mens@jesus.cam.ac.uk

- name: Lena Moore
  pic: 2017-Lena-Moore
  position: LGBT+ Welfare
  social:
    - title: paper-plane
      url: mailto:mcr-lgbt@jesus.cam.ac.uk

- name: Natalia Elvira Astoreca
  pic: 2017-Natalia-Elvira
  position: International Welfare
  social:
    - title: paper-plane
      url: mailto:mcr-international@jesus.cam.ac.uk

- name: Cai Read
  pic: 2017-Cai-Read
  position: Academic Officer
  social:
    - title: paper-plane
      url: mailto:mcr-academic@jesus.cam.ac.uk

- name: Cynthia Larbey
  pic: 2017-Cynthia-Larbey
  position: Green Officer
  social:
    - title: paper-plane
      url: mailto:mcr-green@jesus.cam.ac.uk

- name: Ramsay Bowden
  pic: 2017-Ramsay-Bowden
  position: College Council Representative
  social:
    - title: paper-plane
      url: mailto:mcr-college-council@jesus.cam.ac.uk

- name: Samuel Plummer
  pic: 2017-Samuel-Plummer
  position: Sports Officer
  social:
    - title: paper-plane
      url: mailto:mcr-sports@jesus.cam.ac.uk

- name: Krittika D'Silva
  pic: 2017-Krittika-DSilva 
  position: Webmaster
  social:
    - title: paper-plane
      url: mailto:mcr-webmaster@jesus.cam.ac.uk

- name: Sophia Wild
  pic: 2017-Sophia-Wild
  position: Freshers Representative
  social:
    - title: paper-plane
      url: mailto:mcr-freshers@jesus.cam.ac.uk


# Team names, titles and social links. Any font awesome icon can be used (drop the fa)
fellows:
- name: Dr Sybil Stacpoole
  pic: Fellow-Stacpoole-150x150
  position: Assistant Graduate Tutor
  social:
    - title: paper-plane
      url: mailto:graduate-tutor@jesus.cam.ac.uk

- name: Professor Tim Wilkinson
  pic: Fellow-Tim-150x150
  position: Graduate Tutor
  social:
    - title: paper-plane
      url: mailto:graduate-tutor@jesus.cam.ac.uk

- name: Vanessa Bowman
  pic: Vanessa
  position: Graduate Administrator
  social:
    - title: paper-plane
      url: mailto:graduate-tutor@jesus.cam.ac.uk

- name: Michael Edwards
  pic: Fellow-Edwards-150x150-thumb
  position: Deputy Graduate Tutor
  social:
    - title: paper-plane
      url: mailto:graduate-tutor@jesus.cam.ac.uk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/JesusCollegeCam
  - title: facebook
    url: https://www.facebook.com/groups/jesus.newgrads2011
  - title: github
    url: https://github.com/JJMinton/JesusMCRsite
  - title: linkedin
    url: https://www.linkedin.com/groups?home=&gid=872067&trk=my_groups-tile-grp

# Postal address (add as many lines as necessary)
address:
  - line: Jesus Lane
  - line: Cambridge, CB58BL

# Build settings
markdown: kramdown
permalink: pretty
