url: http://epijim.uk
baseurl: /MCRsite_test

source:      "/Users/Jimmy/JesusMCRsite"
destination: "/Users/Jimmy/MCRsite_test"

# Site settings
title: Jesus College MCR
email: j.ames.a.black@gmail.com
description: "Jesus College MCR (Graduate Society), University of Cambridge."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ed0909
  secondary: 8a0000
  secondary-dark: 333

# Team names, titles and social links. Any font awesome icon can be used (drop the fa)
people:
- name: Rebecca Forster
  pic: Rebecca-Forster-150x150
  position: MCR President
  social:
    - title: paper-plane
      url: mailto:mcr-president@jesus.cam.ac.uk

- name: Chris de Saxe
  pic: Chris-de-Saxe-150x150
  position: Vice-president
  social:
    - title: paper-plane
      url: mailto:mcr-vice-president@jesus.cam.ac.uk

- name: Christine van Hooft
  pic: Christine-van-Hooft-150x150
  position: Secretary
  social:
    - title: paper-plane
      url: mailto:mcr-secretary@jesus.cam.ac.uk

- name: Marcus Webb
  pic: Marcus-Webb-150x150
  position: Treasurer
  social:
    - title: paper-plane
      url: mailto:mcr-treasurer@jesus.cam.ac.uk

- name: Chris Brown
  pic: Chris-Brown-150x150
  position: Social officer
  social:
    - title: paper-plane
      url: mailto:mcr-social@jesus.cam.ac.uk

- name: John Lees
  pic: John-Lees-150x150
  position: Social officer
  social:
    - title: paper-plane
      url: mailto:mcr-social@jesus.cam.ac.uk

- name: Kate Crowcroft
  pic: Kate-Crowcroft-150x150
  position: Women's welfare
  social:
    - title: paper-plane
      url: mailto:mcr-womens@jesus.cam.ac.uk

- name: Junhao Zhang
  pic: Junhao-Zhang-150x150
  position: Men's welfare
  social:
    - title: paper-plane
      url: mailto:mcr-mens@jesus.cam.ac.uk

- name: C.J. Rauch
  pic: CJ-Rauch-150x150
  position: LGBT+ Welfare
  social:
    - title: paper-plane
      url: mailto:mcr-lgbt@jesus.cam.ac.uk

- name: Pu Liu
  pic: Pu-Liu-150x150
  position: International officer
  social:
    - title: paper-plane
      url: mailto:mcr-international@jesus.cam.ac.uk

- name: Jeremy Minton
  pic: Jeremy-Minton-150x150
  position: Academic officer
  social:
    - title: paper-plane
      url: mailto:mcr-academic@jesus.cam.ac.uk

- name: Yee-Chien Chang Webb
  pic: Yee-Chien-Chang-Webb-150x150
  position: Green officer
  social:
    - title: paper-plane
      url: mailto:mcr-green@jesus.cam.ac.uk

- name: Jan Beitner
  pic: Jan-Beitner-150x150
  position: College council
  social:
    - title: paper-plane
      url: mailto:mcr-college-council@jesus.cam.ac.uk

- name: Alex Evans
  pic: Alex-Evans-150x150
  position: Sports officer
  social:
    - title: paper-plane
      url: mailto:mcr-sports@jesus.cam.ac.uk

- name: James Black
  pic: JamesB-150x150
  position: MCR webmaster
  social:
    - title: github
      url: https://github.com/epijim
    - title: paper-plane
      url: mailto:mcr-webmaster@jesus.cam.ac.uk
    - title: info
      url: http://epijim.uk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/JesusCollegeCam
  - title: facebook
    url: https://www.facebook.com/groups/jesus.newgrads2011
  - title: github
    url: https://github.com/epijim/JesusMCRsite
  - title: linkedin
    url: https://www.linkedin.com/groups?home=&gid=872067&trk=my_groups-tile-grp

# Postal address (add as many lines as necessary)
address:
  - line: Jesus Lane
  - line: Cambridge, CB58BL

# Build settings
markdown: kramdown
permalink: pretty
