url: http://0.0.0.0:4000
#baseurl: /agency-jekyll-theme/

# Site settings
title: Jesus College MCR
email: j.ames.a.black@gmail.com
description: "Jesus College MCR (Graduate Society), University of Cambridge."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ed0909
  secondary: 8a0000
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Rebecca Forster
  pic: 1
  position: MCR President (mcr-president)
  social:
    - title: email
      url: test
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Chris de Saxe
  pic: 2
  position: Vice-president
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Christine van Hooft
  pic: 3
  position: Secretary
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Marcus Webb
  pic: 3
  position: Treasurer (mcr-treasurer)
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Chris Brown
  pic: 3
  position: Social officer (mcr-social)
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: John Lees
  pic: 3
  position: Social officer (mcr-social)
  social:
    - title: twitter
      url:
    - title: facebook
      url:
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/JesusCollegeCam
  - title: facebook
    url: https://www.facebook.com/groups/jesus.newgrads2011
  - title: github
    url: http://github.com/epijim

# Postal address (add as many lines as necessary)
address:
  - line: Jesus Lane
  - line: Cambridge, CB58BL

# Build settings
markdown: kramdown
permalink: pretty
