url: http://mcr.jesus.cam.ac.uk
baseurl:

source:      "/Users/Jimmy/JesusMCRsite"
destination: "/Users/Jimmy/MCRsite_test"

# Site settings
title: Jesus College MCR
email: j.ames.a.black@gmail.com
description: "Jesus College MCR (Graduate Society), University of Cambridge."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ed0909
  secondary: 8a0000
  secondary-dark: 333

# Team names, titles and social links. Any font awesome icon can be used (drop the fa)
people:
- name: Rebecca Forster
  pic: Rebecca-Forster-150x150
  position: MCR President
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=aQdyuDi7KG7H2oAxa6G1_N5KhkQaNHytGGuhzg3LD1E=

- name: Chris de Saxe
  pic: Chris-de-Saxe-150x150
  position: Vice-president
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=BjVjndDJCy1j5clAsHoPGwZsF26Z01BiXnH93GM-90mBaykr5bmEsUAFgjdSeY23

- name: Christine van Hooft
  pic: Christine-van-Hooft-150x150
  position: Secretary
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=s9z7dIADNWoax1H0hTLY2pmMl7bqQmfQB1y5mPyp-NY=

- name: Marcus Webb
  pic: Marcus-Webb-150x150
  position: Treasurer
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=HSGVFgyqUuTpXgpbKaHWPcwru6rOMMLIgQZcr7_WnMU=

- name: Chris Brown
  pic: Chris-Brown-150x150
  position: Social officer
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=hZK4Mk1fNQkFU0pc8KqmnoqmebM4rYreCHLtWjktEIc=

- name: John Lees
  pic: John-Lees-150x150
  position: Social officer
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=hZK4Mk1fNQkFU0pc8KqmnoqmebM4rYreCHLtWjktEIc=

- name: Kate Crowcroft
  pic: Kate-Crowcroft-150x150
  position: Women's welfare
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=gRdP7HrS7q6H_9UaOniDlG8LBgc97_eANTCGYNWoPY4=

- name: Dave Bowly
  pic: Dave-150x150
  position: Men's welfare
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=01nSdl5o8KNFEmhrYtN4C-Kw==&c=c3m-YX2_hr5tGx4ugoYOw_O-Oj-W6h0z7gzNeUIQfXY=

- name: C.J. Rauch
  pic: CJ-Rauch-150x150
  position: LGBT+ Welfare
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=-kvR76zRmmVis3kuLgDaoNEs7Ekh0gFRoDOmaFkQZ5I=

- name: Pu Liu
  pic: Pu-Liu-150x150
  position: International officer
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=SQY8J09AaGPG1NYnTNlebzFWZ8fjsCOK70k3yE3uYia1l0vuNk8VUzWKcAJHZ1Xr

- name: Jeremy Minton
  pic: Jeremy-Minton-150x150
  position: Academic officer
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=WWrM2esLbjx5625bc_hLlIVyGyX0rAF6bXR4E28yh3c=

- name: Yee-Chien Chang Webb
  pic: Yee-Chien-Chang-Webb-150x150
  position: Green officer
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=y5IWlfBaTDz_VwDy137-0Q_SzB6h51UpnvC6Qjbdvuc=

- name: Jan Beitner
  pic: Jan-Beitner-150x150
  position: College council
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=XkoLye-sVWSQj1YOq3-VY0tr8UEt1ALcCKJrTNX_MGGjC1u5-v9k4avalobib5nj

- name: Alex Evans
  pic: Alex-Evans-150x150
  position: Sports officer
  social:
    - title: paper-plane
      url: http://www.google.com/recaptcha/mailhide/d?k=017Uowu084OmTuZwWniPbOow==&c=e-pI041rLRnWFInyuaBr5imkpKJsGBigigE6kFRIuG8=

- name: James Black
  pic: JamesB-150x150
  position: MCR webmaster
  social:
    - title: github
      url: https://github.com/epijim
    - title: paper-plane
      url: mailto:mcr-webmaster@jesus.cam.ac.uk
    - title: info
      url: http://epijim.uk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/JesusCollegeCam
  - title: facebook
    url: https://www.facebook.com/groups/jesus.newgrads2011
  - title: github
    url: https://github.com/epijim/JesusMCRsite
  - title: linkedin
    url: https://www.linkedin.com/groups?home=&gid=872067&trk=my_groups-tile-grp

# Postal address (add as many lines as necessary)
address:
  - line: Jesus Lane
  - line: Cambridge, CB58BL

# Build settings
markdown: kramdown
permalink: pretty
