#!/bin/sh


BRANCH=`git rev-parse --abbrev-ref HEAD`

# Check which branch it's on
if [ $BRANCH == "deploy" ]; then

	exec < /dev/tty

    ./_deploy

	read -r -p "Do you want to commit? [Y/n] " response
	if [[ $response  =~ ^([nN][oO]|[nN])$ ]]; then
		echo "Skippping commit"
		exit 1
	else
		echo "Commiting..."
		exit 0
	fi
fi
